from enum import Enum

class ResponseErrorTypes(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    MODEL_NOT_TRAINED = "MODEL_NOT_TRAINED"
    INVALID_FEATURE_VECTOR = "INVALID_FEATURE_VECTOR"
    DATASET_EMPTY = "DATASET_EMPTY"
    DATA_PREPARATION_ERROR = "DATA_PREPARATION_ERROR"
    MODEL_PREDICTION_ERROR = "MODEL_PREDICTION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"